### ISSUE TITLE
snes-ff theme balloon cut off

### ISSUE THREAD

**Issue by klostrophobik** [onimitch/ffxi-balloon-ashitav4#15]
Left side of the snes-ff theme is cut off after the latest update on Horizon (not sure about other servers).  Verified it wasn't just me with a few streamers and ls mates.

Addon version 4.2.1

![image](https://github.com/onimitch/ffxi-balloon-ashitav4/assets/1709958/a0d46f68-9498-47fe-8a36-0eedf2cbc413)

**Comment by klostrophobik** [comment]
Also, there was an update to Ashita by thorny that adjusted text size.  I'm not sure if that has anything to do with it, but this was an ashita level change that could have an impact.

**Comment by onimitch** [comment]
Sorry for the delay, I'll try and take a look at this later and see what's happening.

**Comment by onimitch** [comment]
Hi, fix for this is in [4.2.2](https://github.com/onimitch/ffxi-balloon-ashitav4/releases/tag/4.2.2)
