### ISSUE TITLE
Auto-translate feature

### ISSUE THREAD

**Issue by RicardoFAndres** [onimitch/ffxi-balloon-ashitav4#17]
Hello!
I remember a post in the Ashita Discord about a guy trying to add to Balloon a autotranslate feature (english to chinese) using Baidu. You entered to the conversation talking about the project but few months hass passed and no news about this feature.
Are you planning to do something similar? A lot of people would play the game if it had a translator like Tataru and Balloon is perfect for that. For example, a lot of Spanish people would play it, since English scares them away.
Thx for your work, is awesome!

**Comment by onimitch** [comment]
Sorry but I don't have any plans to build anything like that, in Balloon or otherwise.
