### ISSUE TITLE
Balloon tests failing in HorizonXI

### ISSUE THREAD

**Issue by Tavo5691** [onimitch/ffxi-balloon-ashitav4#7]
Just installed version 4.0.4 and wanted to run the tests cases to check my config, running any test causes the addon to unload

![balloon-error](https://github.com/onimitch/ffxi-balloon-ashitav4/assets/20252993/f5560ba1-ce9f-4b2b-8705-4016786ca104)

I'm not sure if other addons could cause this but changing line 619 to this seems to fix the issue, at least for me:

`local message_prefix = (npc_name ~= '' and npc_name .. ' : ') or ''
`

That ensures **message_prefix** is not boolean before concatenating in line 620.

**Comment by onimitch** [comment]
Thanks for this. It does indeed look like a syntax error, thanks for spotting it. I made a last minute change to tidy that code up and must have not tested it fully, apologies.

I’ll apply your fix in a release tomorrow.

**Comment by onimitch** [comment]
Fixed in [4.0.4](https://github.com/onimitch/ffxi-balloon-ashitav4/releases/tag/4.0.4)
